"""
Orchestrator – run all Contoso data generators in the correct order.

Usage:
    python generate_all.py                     # output to ./output
    python generate_all.py --output-dir /tmp/demo  # custom output dir
    DATAGEN_OUTPUT_DIR=/data python generate_all.py
"""

import argparse
import os
import sys
import time

# Ensure the generators directory is on sys.path so imports work when
# this script is invoked from any working directory.
_SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
if _SCRIPT_DIR not in sys.path:
    sys.path.insert(0, _SCRIPT_DIR)

import config as cfg


def _run_step(label: str, fn) -> None:
    """Run a generator function, print progress and elapsed time."""
    print(f"\n{'='*60}")
    print(f"  {label}")
    print(f"{'='*60}")
    t0 = time.perf_counter()
    fn()
    elapsed = time.perf_counter() - t0
    print(f"  ⏱  {elapsed:.1f}s")


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Generate all Contoso demo datasets."
    )
    parser.add_argument(
        "--output-dir",
        default=None,
        help="Directory for parquet output (default: ./output or DATAGEN_OUTPUT_DIR env var)",
    )
    args = parser.parse_args()

    # Override config output dir if flag is provided
    if args.output_dir:
        cfg.OUTPUT_DIR = args.output_dir

    os.makedirs(cfg.OUTPUT_DIR, exist_ok=True)
    print(f"Output directory: {os.path.abspath(cfg.OUTPUT_DIR)}")
    print(f"Seed: {cfg.SEED}")

    t_total = time.perf_counter()

    # ------------------------------------------------------------------
    # Phase 1 — Dimensions (no cross-dataset dependencies among these)
    # ------------------------------------------------------------------
    from gen_customers import main as gen_customers_main
    from gen_products import main as gen_products_main
    from gen_stores import main as gen_stores_main
    from gen_hr_employees import main as gen_employees_main
    from gen_supply_chain import generate_suppliers, generate_warehouses

    _run_step("1/8  Customers", gen_customers_main)
    _run_step("2/8  Products", gen_products_main)
    _run_step("3/8  Stores", gen_stores_main)
    _run_step("4/8  Employees", gen_employees_main)

    # Suppliers & warehouses are dimensions generated by the supply-chain module
    def _gen_suppliers_warehouses():
        import pandas as pd
        for name, gen_fn in [
            ("suppliers", generate_suppliers),
            ("warehouses", generate_warehouses),
        ]:
            df = gen_fn()
            path = os.path.join(cfg.OUTPUT_DIR, f"{name}.parquet")
            df.to_parquet(path, index=False, engine="pyarrow")
            print(f"  ✓ {len(df):,} rows → {path}")

    _run_step("5/8  Suppliers & Warehouses", _gen_suppliers_warehouses)

    # ------------------------------------------------------------------
    # Phase 2 — Facts (reference dimension IDs)
    # ------------------------------------------------------------------
    from gen_sales_transactions import main as gen_sales_main
    from gen_inventory import main as gen_inventory_main
    from gen_supply_chain import generate_supply_relationships, generate_shipments

    _run_step("6/8  Sales Transactions", gen_sales_main)
    _run_step("7/8  Inventory", gen_inventory_main)

    def _gen_sc_facts():
        import pandas as pd
        for name, gen_fn in [
            ("supply_relationships", generate_supply_relationships),
            ("shipments", generate_shipments),
        ]:
            df = gen_fn()
            path = os.path.join(cfg.OUTPUT_DIR, f"{name}.parquet")
            df.to_parquet(path, index=False, engine="pyarrow")
            print(f"  ✓ {len(df):,} rows → {path}")

    _run_step("8/9  Supply Chain Relationships & Shipments", _gen_sc_facts)

    from gen_iot_telemetry import main as gen_iot_main
    _run_step("9/9  IoT Telemetry", gen_iot_main)

    # ------------------------------------------------------------------
    # Summary
    # ------------------------------------------------------------------
    total_elapsed = time.perf_counter() - t_total
    print(f"\n{'='*60}")
    print(f"  ✅  All datasets generated in {total_elapsed:.1f}s")
    print(f"  📁  {os.path.abspath(cfg.OUTPUT_DIR)}")
    print(f"{'='*60}")

    # List generated files
    files = sorted(f for f in os.listdir(cfg.OUTPUT_DIR) if f.endswith(".parquet"))
    for f in files:
        size_mb = os.path.getsize(os.path.join(cfg.OUTPUT_DIR, f)) / (1024 * 1024)
        print(f"    {f:<40s} {size_mb:>8.2f} MB")


if __name__ == "__main__":
    main()
