/**
 * Tales & Timber IoT Edge Simulator — Configuration
 *
 * This streaming container is responsible for IoT sensor telemetry ONLY.
 * POS transactions and inventory events are generated by the OLTP simulator
 * (simulator/) which writes directly to the Fabric SQL Database.  Those
 * changes reach Eventhouse automatically via Fabric SQL Database Change Event
 * Streaming → Eventstream — no duplicate event generators needed.
 */

import dotenv from "dotenv";

dotenv.config();

/**
 * Generates a sequential array of zero-padded IDs.
 * @param prefix - The prefix for each ID (e.g. "S-")
 * @param count - How many IDs to generate
 * @param padLength - Total digit length after the prefix
 * @returns Array of formatted IDs
 */
function generateIdRange(prefix: string, count: number, padLength: number): string[] {
  return Array.from({ length: count }, (_, i) =>
    `${prefix}${String(i + 1).padStart(padLength, "0")}`
  );
}

/**
 * Application configuration loaded from environment variables with sensible
 * defaults.  Only IoT-related settings remain — POS and inventory generation
 * has moved to the OLTP simulator (see simulator/oltp_simulator.py).
 */
export interface AppConfig {
  /** Event Hubs connection string. Required when DRY_RUN is false. */
  eventHubConnectionString: string;
  /** Event Hub name / topic. */
  eventHubName: string;
  /** When true, events are logged to the console instead of being sent to Event Hubs. */
  dryRun: boolean;
  /** Target IoT telemetry events per second. */
  iotEventsPerSecond: number;
  /** Available store IDs (S-001 … S-150). */
  storeIds: string[];
}

/**
 * Loads configuration from environment variables, falling back to defaults
 * where appropriate.  Throws if EVENT_HUB_CONNECTION_STRING is missing
 * while DRY_RUN is false.
 */
export function loadConfig(): AppConfig {
  const dryRun = (process.env["DRY_RUN"] ?? "true").toLowerCase() === "true";
  const eventHubConnectionString = process.env["EVENT_HUB_CONNECTION_STRING"] ?? "";

  if (!dryRun && !eventHubConnectionString) {
    throw new Error(
      "EVENT_HUB_CONNECTION_STRING is required when DRY_RUN is false"
    );
  }

  return {
    eventHubConnectionString,
    eventHubName: process.env["EVENT_HUB_NAME"] ?? "tales-and-timber-events",
    dryRun,
    iotEventsPerSecond: parseInt(process.env["IOT_EVENTS_PER_SECOND"] ?? "10", 10),
    storeIds: generateIdRange("S-", 150, 3),
  };
}
