/**
 * Contoso IoT Edge Simulator
 *
 * Generates real-time IoT sensor telemetry (temperature, humidity, foot
 * traffic, energy, door counters) and sends it to Azure Event Hubs.
 *
 * Architecture note:
 * This container is responsible for IoT telemetry ONLY.  POS transactions
 * and inventory events are generated by the OLTP simulator (simulator/)
 * which writes to the Fabric SQL Database.  Those changes reach Eventhouse
 * automatically via Fabric SQL Database Change Event Streaming → Eventstream.
 *
 *   IoT sensors   →  this container  →  Event Hubs  →  Eventstream  →  Eventhouse
 *   POS / Inventory  →  OLTP simulator  →  SQL Database  →  Change Event Streaming  →  Eventstream  →  Eventhouse
 */

import { EventHubProducerClient } from "@azure/event-hubs";
import { loadConfig } from "./config.js";
import type { AppConfig } from "./config.js";
import { generateIoTEvent } from "./generators/iot_sensors.js";
import type { IoTEvent } from "./generators/iot_sensors.js";

/** Cumulative event counter for stats logging. */
interface EventCounters {
  iot: number;
}

const counters: EventCounters = { iot: 0 };

/** Handles for active intervals so we can clean up on shutdown. */
const activeIntervals: NodeJS.Timeout[] = [];

/** Optional Event Hub producer — only initialised when DRY_RUN is false. */
let producer: EventHubProducerClient | undefined;

/**
 * Sends or logs a batch of events depending on the current run mode.
 *
 * @param events - Array of events to dispatch
 * @param config - Application configuration
 */
async function dispatchEvents(events: IoTEvent[], config: AppConfig): Promise<void> {
  if (config.dryRun) {
    for (const event of events) {
      console.log(JSON.stringify(event));
    }
    return;
  }

  if (!producer) return;

  const batch = await producer.createBatch();
  for (const event of events) {
    const added = batch.tryAdd({ body: event });
    if (!added) {
      // Current batch is full — send it and start a new one
      await producer.sendBatch(batch);
      const newBatch = await producer.createBatch();
      if (!newBatch.tryAdd({ body: event })) {
        console.error("Event too large for a single batch:", event.eventType);
      }
    }
  }
  if (batch.count > 0) {
    await producer.sendBatch(batch);
  }
}

/**
 * Starts the IoT generator that produces events at the specified rate.
 *
 * @param config - Application configuration
 */
function startIoTGenerator(config: AppConfig): void {
  const intervalId = setInterval(() => {
    const rate = config.iotEventsPerSecond;
    const events: IoTEvent[] = [];
    for (let i = 0; i < rate; i++) {
      events.push(generateIoTEvent(config));
    }
    counters.iot += events.length;
    dispatchEvents(events, config).catch((err: unknown) => {
      console.error("[IoT Sensors] Failed to dispatch events:", err);
    });
  }, 1000);

  activeIntervals.push(intervalId);
  console.log(`[IoT Sensors] Started — ${config.iotEventsPerSecond} events/s`);
}

/**
 * Logs cumulative event counts every `intervalSeconds` seconds.
 * @param intervalSeconds - Seconds between each stats line
 */
function startStatsLogger(intervalSeconds: number): void {
  const intervalId = setInterval(() => {
    console.log(`[stats] IoT: ${counters.iot}`);
  }, intervalSeconds * 1000);

  activeIntervals.push(intervalId);
}

/**
 * Gracefully shuts down the generator and the Event Hub producer.
 * Called on SIGINT / SIGTERM.
 */
async function shutdown(): Promise<void> {
  console.log("\nShutting down IoT generator…");

  for (const id of activeIntervals) {
    clearInterval(id);
  }

  if (producer) {
    console.log("Closing Event Hub connection…");
    await producer.close();
  }

  console.log(`Final counts — IoT: ${counters.iot}`);

  process.exit(0);
}

/**
 * Main entry point.
 * Loads configuration, optionally connects to Event Hubs, starts the IoT
 * sensor generator, and waits for a shutdown signal.
 */
async function main(): Promise<void> {
  const config = loadConfig();

  console.log("=== Contoso IoT Edge Simulator ===");
  console.log(`Mode: ${config.dryRun ? "DRY RUN (console only)" : "LIVE (sending to Event Hubs)"}`);
  console.log(`Rate — IoT: ${config.iotEventsPerSecond}/s`);
  console.log(`Stores: ${config.storeIds.length}`);
  console.log("");
  console.log("NOTE: POS transactions and inventory events are handled by the OLTP");
  console.log("simulator (simulator/) → SQL Database → Change Event Streaming.");

  if (!config.dryRun) {
    producer = new EventHubProducerClient(
      config.eventHubConnectionString,
      config.eventHubName,
    );
    console.log(`Connected to Event Hub: ${config.eventHubName}`);
  }

  // Register shutdown handlers
  process.on("SIGINT", () => void shutdown());
  process.on("SIGTERM", () => void shutdown());

  // Start IoT sensor generator (the only generator in this container)
  startIoTGenerator(config);

  // Log stats every 10 seconds
  startStatsLogger(10);

  console.log("\nIoT generator running. Press Ctrl+C to stop.\n");
}

main().catch((err: unknown) => {
  console.error("Fatal error:", err);
  process.exit(1);
});
